language: python
branches:
  only:
    - master
    - develop
    - "/v\\d+\\.\\d+\\.\\d+/"
python:
  - '3.6'
install:
  - pip install .
  - pip install nose
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=testing_travis
after_success:
  - coveralls
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: X0NI+Wo08PnAqiVMyApGOsmmZW+IMPde2ywcmQUezdGfVnVVkVoK1kAfLlKlQpr/wGDEVexn+NRNybTUXlZ/dl+nR87f/lHOeAXXD/Hqs0yPWnT0tiyTce9fJ3qSWlEBuVZxfllBk3Mg2EodDX6SKa2iYlTZTmt/jmUqsEI9DE1jBi6AK8mvbssxgPjvYszHPqdt/qJ8zpQHIdYKikM1Kt1mJkQcJUbCOc9yPfy22Ml8B8l1wsfU2vx1MG9MYpTq2yPtW0Uz3+xkf8xomPTESHwd/1wWvzWB0g2HPb+FdsO51fLW/GK29ds5bAXV5mJNuWWuX6Cz7NdrDwIALBSXKRGi3u9FQ3VcDmAjRdtTw3V2hhNmGykW//kHugJlJqXAEPfyj1XH/bmVs3urXcT/uJYP00D5Id4bLgAjVjaeaXnUKevLi5Buj0/atxBpkR1hwQuT2CPoy/2BmpOkAWY1Zmcny2B05uGC5eI1zbflsRY9LyBzvdcQD9HzBZHIeNGyH8d7Be+Cin8n8Rc5mnwr5KDwnBVwkmkHlb2bECiOorFKI96NK51pJuoVS9eX/gvbxoCLSjEZHFQR6wjdTs2FxMF8odePS3ppw5IxQ/js4OdFBjCzji+R4kGQsm9hcECqggtvhv7q28OSYHfPn77waxypaERKC/oWy5nh5/4j4b0=
  on:
    tags: true
    branch: master
